apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serenamarie125-poi-map-app-dev
  annotations:
    argocd/app-name: serenamarie125-poi-map-app-dev
    backstage.io/kubernetes-id: serenamarie125-poi-map-app-dev
    backstage.io/kubernetes-namespace: serenamarie125
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=serenamarie125-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton-enabled : 'false'
    github.com/project-slug: Summit23Janus1/serenamarie125-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/serenamarie125/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/serenamarie125/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/serenamarie125-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://poi-map-app-serenamarie125.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/serenamarie125"
  system: workshop-system-serenamarie125
  consumesApis:
    - gateway-api-serenamarie125
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-serenamarie125
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/serenamarie125"
